#Consul Client Configuration
ro.discovery.server.host=consul
ro.discovery.server.port=8500
ro.discovery.server.register=true
ro.discovery.server.preferIPAddress=true
ro.discovery.service.name=grpc-server-service
#spring.cloud.consul.host=localhost
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.prefer-ip-address=true

#Eureka Client Configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.instance.lease-renewal-interval-in-seconds=5
#eureka.instance.lease-expiration-duration-in-seconds=10
#eureka.client.healthcheck.enabled=true
#spring.cloud.inetutils.preferred-networks=10.0.9.0/24

#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF

#Grpc Server config
ro.grpc.server.port=8090
ro.server.port=8091

#Log config
# ro.logging.appPackages can contain multiple package names with separate log levels for each package
ro.logging.appPackages={"com.rico.grpc.server": "INFO"}
ro.logging.supressStackTrace=false
ro.logging.writeTo=CONSOLE
ro.logging.rootLogger=true
ro.logging.rootLogger.logLevel=INFO
