version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    volumes:
      - consul_data:/consul/data
    ports:
      - "8500:8500" # Consul UI and HTTP API
      - "8600:8600" # DNS Interface
    networks:
      - eureka-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - CONSUL_BIND_INTERFACE=eth0

volumes:
  consul_data:

networks:
  eureka-network:
    external: true
