#Log config
# ro.logging.appPackages can contain multiple package names with separate log levels for each package
ro.logging.appPackages={"com.rico.empty": "DEBUG"}
ro.logging.writeTo=CONSOLE
ro.logging.rootLogger=true
ro.logging.rootLogger.logLevel=INFO

spring.application.name=eureka-server-service
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#spring.cloud.inetutils.preferred-networks=10.0.9.0/24

logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
