#Consul Client Configuration
ro.discovery.server.host=consul
ro.discovery.server.port=8500
ro.discovery.server.register=false
ro.discovery.service.name=grpc-client-service
#spring.cloud.consul.host=localhost
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.register=false

#Eureka configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=true
#eureka.instance.lease-renewal-interval-in-seconds=5
#eureka.instance.lease-expiration-duration-in-seconds=10
#spring.cloud.inetutils.preferred-networks=10.0.9.0/24

#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF

#Grpc Client config
ro.grpc.client.targets={"server1": "grpc-server-service:8090"}
ro.grpc.client.target.serviceType=discovery
ro.server.port=8762
#Log config
# ro.logging.appPackages can contain multiple package names with separate log levels for each package
ro.logging.appPackages={"com.rico.grpc.client": "INFO"}
ro.logging.supressStackTrace=false
ro.logging.writeTo=CONSOLE
ro.logging.rootLogger=true
ro.logging.rootLogger.logLevel=INFO

management.endpoint.health.show-details=always
management.health.grpcChannel.enabled=false